service:
  name: todos
  disabledDeprecations:
    - '*' # To disable all deprecation messages


plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
    
provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: "*"    
  
functions:
  createTodo:
    handler: src/functions/createTodo.handle
    events:
      - http:
          path: /createTodo/{user_id}
          method: POST
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb: Query
          - dynamodb: PutItem       
        Resource: 'arn:aws:dynamodb:${self.provider.region}:*:table/users_todos'

  listTodo:
    handler: src/functions/listTodo.handle
    events:
      - http:
          path: /listTodo/{user_id}
          method: GET
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb: Query          
        Resource: 'arn:aws:dynamodb:${self.provider.region}:*:table/users_todos'


resources:
  Resources:
    dbTodosUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users_todos
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: id
            AttributeType: S          
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
          
